name: publish

on:
  release:
    branch: main
    types: [released]

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: publish
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        registry-url: 'https://registry.npmjs.org'
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install build
    - name: Build the package
      run: python -m build
    - name: Prepare the PyPi dist
      run: mkdir _dist_ && mv dist/*.js* _dist_
    - name: Publish the package to PyPi
      uses: pypa/gh-action-pypi-publish@release/v1
    - name: Prepare the npm dist
      run: mv dist/* _dist_ && mv _dist_/*.js* dist
    - run: npm ci
    - name: Publish the package to npm
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
